format = """
[░▒▓](dark-bright-white)\
[](bg:dark-bright-white fg:dark-black)\
[](bg:dark-bright-blue fg:dark-bright-white)\
$directory\
[](fg:dark-bright-blue bg:dark-blue)\
$conda\
$git_branch\
$git_status\
[](fg:dark-blue bg:dark-cyan)\
$nodejs\
$rust\
$golang\
$java\
$c\
$gradle\
$scala\
[](fg:dark-cyan bg:dark-green)\
$time\
[](fg:dark-green bg:green)\
$cmd_duration\
[ ](fg:green)\
"""

continuation_prompt = '[>](dark-blue) '

palette = "gruvbox-dark"

[palettes.gruvbox-dark]
background = "#282828"
black = "#282828"
blue = "#458588"
bright-black = "#928374"
bright-blue = "#83A598"
bright-cyan = "#8EC07C"
bright-green = "#B8BB26"
bright-purple = "#D3869B"
bright-red = "#FB4934"
bright-white = "#EBDBB2"
bright-yellow = "#FABD2F"
cyan = "#689D6A"
foreground = "#EBDBB2"
green = "#98971A"
name = "Gruvbox Dark"
purple = "#B16286"
red = "#CC241D"
white = "#A89984"
yellow = "#D79921"
dark-black = "#1d2021"
dark-blue = "#32707D"
dark-bright-black = "#7c6f64"
dark-bright-blue = "#458588"
dark-bright-cyan = "#427b58"
dark-bright-green = "#79740e"
dark-bright-purple = "#8f3f71"
dark-bright-red = "#9d2021"
dark-bright-white = "#c9b99a"
dark-bright-yellow = "#b57614"
dark-cyan = "#427b58"
dark-foreground = "#c9b99a"
dark-green = "#79740e"
dark-purple = "#8f3f71"
dark-red = "#9d2021"
dark-white = "#7c6f64"
dark-yellow = "#b57614"

[directory]
style = "fg:bright-white bg:dark-bright-blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "


[conda]
symbol = "🅒"
style = "bg:dark-blue"
ignore_base = false
format = '[[$symbol $environment](fg:bright-white bg:dark-blue)]($style)'

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:bright-white bg:dark-blue)]($style)'

[git_status]
style = "bg:dark-blue"
format = '[[($all_status$ahead_behind )](fg:bright-white bg:dark-blue)]($style)'

[nodejs]
symbol = ""
style = "bg:dark-cyan"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-cyan)]($style)'

[rust]
symbol = ""
style = "bg:dark-cyan"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-cyan)]($style)'

[golang]
symbol = ""
style = "bg:dark-cyan"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-cyan)]($style)'

[java]
symbol = ""
style = "bg:dark-bright-green"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-bright-green)]($style)'

[c]
symbol = ""
style = "bg:dark-bright-green"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-bright-green)]($style)'

[gradle]
style = "bg:dark-bright-green"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-bright-green)]($style)'

[scala]
symbol = ""
style = "bg:dark-bright-green"
format = '[[ $symbol ($version) ](fg:bright-white bg:dark-bright-green)]($style)'

[time]
disabled = false
time_format = "%R"                                              # Hour:Minute Format
style = "bg:dark-green"
format = '[[  $time ](fg:bright-white bg:dark-green)]($style)'

[cmd_duration]
style = "fg:bright-white bg:green"
format = '[ 󱦟 $duration ]($style)'
